version: "3"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - ./database/volumes/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M