version: '3'

services:
  go-server:
    build: .
    environment:
      - PORT=5000
      - DOMAIN=localhost:5000
      - DB_ADDRESS=redis:6379
      - DB_PASSWORD=
      - API_QUOTA=10
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
    environment:
      - REDIS_PASSWORD=
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
